# Generated by Django 6.0.5 on 2026-05-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=100)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
                ('activo', models.CharField(db_column='activo', default='1', max_length=1)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(db_column='id_pedido', primary_key=True, serialize=False)),
                ('codigo', models.CharField(blank=True, db_column='codigo', max_length=100, null=True)),
                ('estado', models.CharField(db_column='estado', default='En Preparación', max_length=50)),
                ('tipo_entrega', models.CharField(blank=True, db_column='tipo_entrega', max_length=100, null=True)),
                ('total', models.DecimalField(blank=True, db_column='total', decimal_places=2, max_digits=12, null=True)),
                ('costo_despacho', models.DecimalField(blank=True, db_column='costo_despacho', decimal_places=2, max_digits=12, null=True)),
                ('total_final', models.DecimalField(blank=True, db_column='total_final', decimal_places=2, max_digits=12, null=True)),
                ('region', models.CharField(blank=True, db_column='region', max_length=100, null=True)),
                ('direccion_entrega', models.CharField(blank=True, db_column='direccion_entrega', max_length=255, null=True)),
                ('fecha_pedido', models.DateTimeField(blank=True, db_column='fecha_pedido', null=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, db_column='fecha_entrega', null=True)),
            ],
            options={
                'db_table': 'pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id_detalle', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='cantidad')),
                ('precio_unitario', models.DecimalField(db_column='precio_unitario', decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(db_column='subtotal', decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'detalle_pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(db_column='id_producto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='nombre', max_length=200)),
                ('descripcion', models.CharField(blank=True, db_column='descripcion', max_length=200, null=True)),
                ('precio', models.DecimalField(db_column='precio', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(db_column='stock', default=0)),
                ('imagen_url', models.CharField(blank=True, db_column='imagen_url', max_length=500, null=True)),
                ('activo', models.CharField(db_column='activo', default='1', max_length=1)),
                ('fecha_creacion', models.DateTimeField(blank=True, db_column='fecha_creacion', null=True)),
            ],
            options={
                'db_table': 'producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(db_column='id_usuario', primary_key=True, serialize=False)),
                ('id_rol', models.IntegerField(blank=True, db_column='id_rol', null=True)),
                ('nombre', models.CharField(db_column='nombre', max_length=150)),
                ('apellido', models.CharField(blank=True, db_column='apellido', max_length=150, null=True)),
                ('email', models.CharField(blank=True, db_column='email', max_length=254, null=True)),
                ('contrasena', models.CharField(db_column='contrasena', max_length=128)),
                ('telefono', models.CharField(blank=True, db_column='telefono', max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, db_column='direccion', max_length=255, null=True)),
                ('activo', models.CharField(db_column='activo', default='1', max_length=1)),
                ('fecha_registro', models.DateTimeField(blank=True, db_column='fecha_registro', null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
